openapi: 3.0.1
info:
  title: cocotola
  description: cocotola
  version: 1.0.0
  contact:
    name: API Support
    email: support@swagger.io
    url: http://www.swagger.io/support
tags:
  - name: auth
paths:
  /auth/api/v1/password/authenticate:
    post:
      summary: Password Authentication
      deprecated: false
      description: Password Authentication
      operationId: passwordAuthentication
      tags:
        - auth
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordAuthRequest'
            examples: {}
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
          headers: {}
      security: []
  /auth/api/v1/profile/me:
    get:
      summary: Get My Profile
      deprecated: false
      description: Get my profile
      operationId: getMyProfile
      tags:
        - auth
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMyProfileResponse'
          headers: {}
      security:
        - BearerAuth: []
  /auth/api/v1/guest/authenticate:
    post:
      summary: Guest Authentication
      deprecated: false
      description: Guest Authentication
      operationId: guestAuthentication
      tags:
        - auth
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GuestAuthRequest'
            examples: {}
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
          headers: {}
      security: []
  /auth/api/v1/user:
    post:
      summary: Create User
      deprecated: false
      description: Create a new user
      operationId: createUser
      tags:
        - auth
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
components:
  schemas:
    PasswordAuthRequest:
      type: object
      properties:
        loginId:
          type: string
          x-go-name: LoginID
          x-go-custom-tag: binding:"required"
          pattern: ^.*$
        password:
          type: string
          x-go-custom-tag: binding:"required"
          pattern: ^.*$
        organizationName:
          type: string
          x-go-custom-tag: binding:"required"
          pattern: ^.*$
      required:
        - loginId
        - password
        - organizationName
    AuthResponse:
      type: object
      properties:
        accessToken:
          type: string
          pattern: ^.*$
        refreshToken:
          type: string
          pattern: ^.*$
      required:
        - accessToken
        - refreshToken
    GetMyProfileResponse:
      type: object
      properties:
        loginId:
          type: string
          x-go-name: LoginID
        username:
          type: string
        organizationId:
          type: integer
          x-go-name: OrganizationID
          format: int32
        organizationName:
          type: string
        personalSpaceId:
          type: integer
          format: int32
          x-go-name: PersonalSpaceID
          nullable: true
      required:
        - loginId
        - username
        - organizationId
        - organizationName
    GuestAuthRequest:
      type: object
      properties:
        organizationName:
          type: string
          pattern: ^[A-Za-z0-9-]{1,20}$
          maxLength: 20
          x-oapi-codegen-extra-tags:
            binding: required,min=1,max=20
          minLength: 1
      required:
        - organizationName
    CreateUserRequest:
      type: object
      properties:
        loginId:
          type: string
          x-go-name: LoginID
          x-go-custom-tag: binding:"required,email"
        username:
          type: string
          pattern: ^.*$
        password:
          type: string
          pattern: ^.*$
      required:
        - loginId
        - username
        - password
  responses: {}
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
servers: []
security: []
