---
app:
  auth:
    signingKey: ${APP_AUTH_SIGNING_KEY}
    accessTokenTtlMin: ${APP_AUTH_ACCESS_TOKEN_TTL_MIN:-5}
    refreshTokenTtlHour: ${APP_AUTH_REFRESH_TOKEN_TTL_HOUR:-720}
server:
  httpPort: ${APP_HTTP_PORT:-8000}
  metricsPort: ${APP_METRICS_PORT:-8001}
  readHeaderTimeoutSec: ${APP_READ_HEADER_TIMEOUT_SEC:-30}
  gin:
    cors:
      allowOrigins: ${CORS_ALLOW_ORIGINS:-'*'}
      allowMethods: ${CORS_ALLOW_METHODS:-'GET,POST,PUT,DELETE,OPTIONS'}
      allowHeaders: ${CORS_ALLOW_HEADERS:-'Content-Type'}
    log:
      accessLog: ${APP_GIN_LOG_ACCESS_LOG:-true}
      accessLogRequestBody: ${APP_GIN_LOG_ACCESS_LOG_REQUEST_BODY:-false}
      accessLogResponseBody: ${APP_GIN_LOG_ACCESS_LOG_RESPONSE_BODY:-false}
    debug:
      gin: ${APP_GIN_DEBUG_GIN:-false}
      wait: ${APP_GIN_DEBUG_WAIT:-false}
  shutdown:
    timeSec1: ${APP_SHUTDOWN_TIME_SEC1:-1}
    timeSec2: ${APP_SHUTDOWN_TIME_SEC2:-1}
db:
  driverName: ${APP_DB_DRIVER_NAME:-sqlite3}
  sqlite3:
    file: ${APP_SQLITE3_FILE:-app.db}
  mysql:
    username: ${APP_MYSQL_USERNAME}
    password: ${APP_MYSQL_PASSWORD}
    host: ${APP_MYSQL_HOST:-127.0.0.1}
    port: ${APP_MYSQL_PORT:-3306}
    database: ${APP_MYSQL_DATABASE:-local}
  postgres:
    username: ${APP_POSTGRES_USERNAME}
    password: ${APP_POSTGRES_PASSWORD}
    host: ${APP_POSTGRES_HOST:-127.0.0.1}
    port: ${APP_POSTGRES_PORT:-5432}
    database: ${APP_POSTGRES_DATABASE:-postgres}
trace:
  exporter: ${TRACE_EXPORTER:-none}
  google:
    projectId: ${TRACE_GOOGLE_PROJECT_ID}
  otlp:
    endpoint: ${TRACE_OTLP_ENDPOINT}
    insecure: ${TRACE_OTLP_INSECURE:-true}
log:
  level: ${APP_LOG_LEVEL:-info}
  exporter: ${APP_LOG_EXPORTER:-none}
